"""add checkins and checkInTasks

Revision ID: f2ee3752d974
Revises: c5779dc15d70
Create Date: 2023-10-07 16:09:39.462871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ee3752d974'
down_revision = 'c5779dc15d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkIns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('happy', sa.Boolean(), nullable=False),
    sa.Column('meh', sa.Boolean(), nullable=False),
    sa.Column('sad', sa.Boolean(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkInTasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taskId', sa.Integer(), nullable=True),
    sa.Column('checkInId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checkInId'], [''], ),
    sa.ForeignKeyConstraint(['taskId'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkInTasks')
    op.drop_table('checkIns')
    # ### end Alembic commands ###