"""check_ins and check_in_tasks table name update

Revision ID: 4331d7e53581
Revises: 3a63a43a94dc
Create Date: 2023-10-17 18:23:11.274965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4331d7e53581'
down_revision = '3a63a43a94dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('mood', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check_in_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taskId', sa.Integer(), nullable=True),
    sa.Column('checkInId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checkInId'], ['check_ins.id'], ),
    sa.ForeignKeyConstraint(['taskId'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('checkInTasks')
    op.drop_table('checkIns')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkIns',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userId', sa.INTEGER(), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('month', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.INTEGER(), nullable=False),
    sa.Column('mood', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkInTasks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('taskId', sa.INTEGER(), nullable=True),
    sa.Column('checkInId', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['checkInId'], ['checkIns.id'], ),
    sa.ForeignKeyConstraint(['taskId'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('check_in_tasks')
    op.drop_table('check_ins')
    # ### end Alembic commands ###